// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/L1.h"
#include "Commands/L2.h"
#include "Commands/L3.h"
#include "Commands/L4.h"
#include "Commands/Motor_Control.h"
#include "Commands/Servo_Control.h"
#include "Commands/Toggle_Solonoid.h"
#include "Commands/Write_Sensors.h"


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

OI::OI() {
	// Process operator interface input here.
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

	xbox = new Joystick(0);
	
	level4 = new JoystickButton(xbox, 8);
	level4->WhenPressed(new L4());
	level3 = new JoystickButton(xbox, 7);
	level3->WhenPressed(new L3());
	level2 = new JoystickButton(xbox, 6);
	level2->WhenPressed(new L2());
	level1 = new JoystickButton(xbox, 5);
	level1->WhenPressed(new L1());
	writeSensorstoConsole = new JoystickButton(xbox, 4);
	writeSensorstoConsole->WhileHeld(new Write_Sensors());
	toggleServos = new JoystickButton(xbox, 3);
	toggleServos->WhenPressed(new Servo_Control());
	toggleDriveTrain = new JoystickButton(xbox, 2);
	toggleDriveTrain->WhenPressed(new Motor_Control());
	solonoid_Toggle = new JoystickButton(xbox, 1);
	solonoid_Toggle->WhenPressed(new Toggle_Solonoid());
     

        // SmartDashboard Buttons
	SmartDashboard::PutData("Toggle_Solonoid", new Toggle_Solonoid());

	SmartDashboard::PutData("Motor_Control", new Motor_Control());

	SmartDashboard::PutData("AutonomousCommand", new AutonomousCommand());

	SmartDashboard::PutData("Servo_Control", new Servo_Control());

	SmartDashboard::PutData("Write_Sensors", new Write_Sensors());

	SmartDashboard::PutData("L4", new L4());

	SmartDashboard::PutData("L3", new L3());

	SmartDashboard::PutData("L2", new L2());

	SmartDashboard::PutData("L1", new L1());


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

Joystick* OI::getXbox() {
	return xbox;
}


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
