// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/Autonomous_Command.h"
#include "Commands/Motor_Control.h"
#include "Commands/Servo_Control.h"
#include "Commands/Toggle_Solonoid.h"
#include "Commands/Write_Sensors.h"


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

OI::OI() {
	// Process operator interface input here.
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

	xbox = new Joystick(0);
	
	writeSensorstoConsole = new JoystickButton(xbox, 4);
	writeSensorstoConsole->WhenPressed(new Write_Sensors());
	toggleServos = new JoystickButton(xbox, 3);
	toggleServos->WhenPressed(new Servo_Control());
	toggleDriveTrain = new JoystickButton(xbox, 2);
	toggleDriveTrain->WhenPressed(new Motor_Control());
	x = new JoystickButton(xbox, 1);
	x->WhenPressed(new Toggle_Solonoid());
     

        // SmartDashboard Buttons
	SmartDashboard::PutData("Toggle_Solonoid", new Toggle_Solonoid());

	SmartDashboard::PutData("Motor_Control", new Motor_Control());

	SmartDashboard::PutData("Autonomous_Command", new Autonomous_Command());

	SmartDashboard::PutData("Servo_Control", new Servo_Control());

	SmartDashboard::PutData("Write_Sensors", new Write_Sensors());


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

Joystick* OI::getXbox() {
	return xbox;
}


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
