// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "Servo_Control.h"

Servo_Control::Servo_Control() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

}

// Called just before this Command runs the first time
void Servo_Control::Initialize() {
	
}

// Called repeatedly when this Command is scheduled to run
void Servo_Control::Execute() {


	double x;
	double y;
	//Get X Axis Value
	x = Joystick2->GetX();
	//If X is close to 0, reset it to 0
	if(x<.2 && x>-.2){
		x = 0;
	}

	//Get Y Axis Value
	y = Joystick2->GetY();
	//If Y is close to 0, reset it to 0
	if(y<.2 && y>-.2){
		y = 0;
	}


	//Servo X
	Robot::servos->servoX->Set(x);
	//Servo Y
	Robot::servos->servoY->Set(y);
}

// Make this return true when this Command no longer needs to run execute()
bool Servo_Control::IsFinished() {
	return false;
}

// Called once after isFinished returns true
void Servo_Control::End() {
	
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void Servo_Control::Interrupted() {

}
