// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "Toggle_Solonoid.h"

Toggle_Solonoid::Toggle_Solonoid() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::pneumatics);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

// Called just before this Command runs the first time
void Toggle_Solonoid::Initialize() {
	Robot::pneumatics->Toggle();
	printf("Run");

}

// Called repeatedly when this Command is scheduled to run
void Toggle_Solonoid::Execute() {
	
}

// Make this return true when this Command no longer needs to run execute()
bool Toggle_Solonoid::IsFinished() {
	return true;

}

// Called once after isFinished returns true
void Toggle_Solonoid::End() {
	
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void Toggle_Solonoid::Interrupted() {

}
